### ISSUE TITLE
TP1 Semaine 2 - Question : quel client envoie la commande OPTS ?

### ISSUE THREAD

**Issue by seintur** [youssraaa/TP1_CAR#2]

**Comment by youssraaa** [comment]
Le client FTP envoie automatiquement la commande OPTS pour configurer des options spécifiques du serveur, telles que l'encodage UTF-8. Lors de mes tests, j'ai constaté que cette commande bloquait la connexion si elle n'était pas ignorée, c'est pourquoi j'ai ajouté un code pour l'ignorer et permettre une connexion correcte au serveur.

**Comment by seintur** [comment]
Ma question demeure : quel est le programme client que vous utilisez ? sur Windows ? sur Linux ?

**Comment by youssraaa** [comment]
J'utilise PowerShell sur Windows pour me connecter au serveur FTP.
